### ISSUE TITLE
Cannot create extension process on windows

### ISSUE THREAD

**Issue by tmtt66** [sttor/easysiem-osquery-response-plugin-python#1]
PS C:\Program Files\osquery> .\osqueryi.exe --allow_unsafe --extension .\active_response_extension.py                   E0417 08:07:23.427553  5336 watcher.cpp:623] Cannot create extension process: .\active_response_extension.py

**Comment by KeithLRobertson** [comment]
@tmtt66 Did you solve this? How? I have the same problem.
